sudo: false
language: python

env:
    - CONDA="python=2.7"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --all --yes
    - conda config --add channels ioos -f
    - travis_retry conda create --yes -n test $CONDA --file requirements.txt
    - source activate test
    - travis_retry conda install --yes pytest

script:
    - py.test -vv

notifications:
    flowdock: 2dd835dfbdbc64986ba043fffa654836,1d5af475ae38ec1d874c752c23558d2d
